import type { UnitDef, UnitTypeId, FactionId, DamageType } from './types';

// Range values from the design doc are in a 0-350 "pixel" scale.
// World units are scaled down: 1 world unit ~= 10 design pixels.
const R = 0.1; // range scale factor

export const UNIT_DEFS: Record<UnitTypeId, UnitDef> = {
  // ---- Survivor Corps (green) ----
  scout: {
    id: 'scout',
    name: 'Scout',
    faction: 'survivor',
    color: 0x4ade80,
    hp: 70,
    dmg: 14,
    spd: 2.0,
    range: 140 * R,
    cost: 12,
    attackKind: 'ranged',
    attackCooldown: 0.7,
    damageType: 'bullet',
    armorType: 'flesh',
    description: 'Fast, lightly armed recon trooper with a pistol.',
  },
  rifleman: {
    id: 'rifleman',
    name: 'Rifleman',
    faction: 'survivor',
    color: 0x4ade80,
    hp: 90,
    dmg: 20,
    spd: 1.5,
    range: 150 * R,
    cost: 20,
    attackKind: 'ranged',
    attackCooldown: 0.9,
    damageType: 'bullet',
    armorType: 'flesh',
    description: 'Standard infantry. Reliable assault rifle.',
  },
  heavy: {
    id: 'heavy',
    name: 'Heavy Gunner',
    faction: 'survivor',
    color: 0x4ade80,
    hp: 160,
    dmg: 45,
    spd: 0.8,
    range: 120 * R,
    cost: 55,
    attackKind: 'ranged',
    attackCooldown: 1.3,
    damageType: 'bullet',
    armorType: 'flesh',
    description: 'Slow but devastating minigun operator.',
  },
  medic: {
    id: 'medic',
    name: 'Medic',
    faction: 'survivor',
    color: 0x4ade80,
    hp: 70,
    dmg: 10,
    spd: 1.4,
    range: 100 * R,
    cost: 30,
    attackKind: 'heal',
    attackCooldown: 1.0,
    specialAbility: 'supplyDrop',
    damageType: 'heal',
    armorType: 'flesh',
    description: 'Heals nearby wounded allies over time. Periodic AoE supply drop.',
  },

  // ---- Militia (orange) ----
  biker: {
    id: 'biker',
    name: 'Biker',
    faction: 'militia',
    color: 0xf97316,
    hp: 80,
    dmg: 30,
    spd: 2.8,
    range: 25 * R,
    cost: 25,
    attackKind: 'melee',
    attackCooldown: 0.6,
    damageType: 'bullet',
    armorType: 'flesh',
    description: 'Fast melee berserker with a brutal chain weapon.',
  },
  bomber: {
    id: 'bomber',
    name: 'Bomber',
    faction: 'militia',
    color: 0xf97316,
    hp: 100,
    dmg: 80,
    spd: 1.2,
    range: 60 * R,
    cost: 65,
    attackKind: 'explosive',
    attackCooldown: 1.8,
    specialAbility: 'suicideBomber',
    damageType: 'explosive',
    armorType: 'flesh',
    description: 'Lobs explosives dealing splash area damage. Self-destructs in enemy clusters.',
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper',
    faction: 'militia',
    color: 0xf97316,
    hp: 60,
    dmg: 55,
    spd: 1.1,
    range: 350 * R,
    cost: 48,
    attackKind: 'ranged',
    attackCooldown: 2.0,
    damageType: 'bullet',
    armorType: 'flesh',
    description: 'Extreme range marksman. Devastating but fragile.',
  },

  // ---- Tech Division (cyan) ----
  combatBot: {
    id: 'combatBot',
    name: 'Combat Bot',
    faction: 'tech',
    color: 0x06b6d4,
    hp: 200,
    dmg: 25,
    spd: 1.0,
    range: 130 * R,
    cost: 70,
    attackKind: 'ranged',
    attackCooldown: 0.8,
    damageType: 'energy',
    armorType: 'armored',
    description: 'Durable autonomous combat robot.',
  },
  warDrone: {
    id: 'warDrone',
    name: 'War Drone',
    faction: 'tech',
    color: 0x06b6d4,
    hp: 45,
    dmg: 32,
    spd: 3.0,
    range: 160 * R,
    cost: 40,
    attackKind: 'ranged',
    attackCooldown: 0.6,
    flying: true,
    damageType: 'energy',
    armorType: 'armored',
    description: 'Ultra fast flying gunship drone.',
  },
  mechWalker: {
    id: 'mechWalker',
    name: 'Mech Walker',
    faction: 'tech',
    color: 0x06b6d4,
    hp: 500,
    dmg: 60,
    spd: 0.7,
    range: 150 * R,
    cost: 120,
    attackKind: 'ranged',
    attackCooldown: 1.1,
    scale: 1.6,
    specialAbility: 'overclock',
    damageType: 'energy',
    armorType: 'armored',
    description: 'Boss-tier walker. The pride of the Tech Division. Can overclock.',
  },

  // ---- Enemy only ----
  zombie: {
    id: 'zombie',
    name: 'Zombie',
    faction: 'enemy',
    color: 0x6b7d5a,
    hp: 50,
    dmg: 8,
    spd: 0.8,
    range: 20 * R,
    cost: 0,
    attackKind: 'melee',
    attackCooldown: 1.2,
    damageType: 'melee',
    armorType: 'flesh',
    description: 'Slow shambling Feral. Dangerous in swarms.',
  },
  feral: {
    id: 'feral',
    name: 'Feral',
    faction: 'enemy',
    color: 0x4a3d2f,
    hp: 40,
    dmg: 15,
    spd: 2.2,
    range: 20 * R,
    cost: 0,
    attackKind: 'melee',
    attackCooldown: 0.7,
    damageType: 'melee',
    armorType: 'flesh',
    description: 'Fast, hunched mutant predator.',
  },
  brute: {
    id: 'brute',
    name: 'Mutant Brute',
    faction: 'enemy',
    color: 0x7c3aed,
    hp: 200,
    dmg: 35,
    spd: 1.2,
    range: 30 * R,
    cost: 0,
    attackKind: 'melee',
    attackCooldown: 1.1,
    scale: 1.2,
    damageType: 'melee',
    armorType: 'flesh',
    description: 'Hulking mutant tank with oversized arms.',
  },
  alpha: {
    id: 'alpha',
    name: 'Mutant Alpha',
    faction: 'enemy',
    color: 0x9333ea,
    hp: 800,
    dmg: 60,
    spd: 1.0,
    range: 40 * R,
    cost: 0,
    attackKind: 'melee',
    attackCooldown: 1.0,
    scale: 1.8,
    damageType: 'melee',
    armorType: 'flesh',
    description: 'The mutant warlord. A living fortress.',
  },
  killerBot: {
    id: 'killerBot',
    name: 'Killer Bot',
    faction: 'enemy',
    color: 0xd1d5db,
    hp: 120,
    dmg: 22,
    spd: 1.4,
    range: 140 * R,
    cost: 0,
    attackKind: 'ranged',
    attackCooldown: 0.7,
    damageType: 'energy',
    armorType: 'armored',
    description: 'Precision military robot with a red optic.',
  },
  robotTank: {
    id: 'robotTank',
    name: 'Robot Tank',
    faction: 'enemy',
    color: 0x9ca3af,
    hp: 400,
    dmg: 50,
    spd: 0.6,
    range: 120 * R,
    cost: 0,
    attackKind: 'ranged',
    attackCooldown: 1.4,
    scale: 1.3,
    damageType: 'energy',
    armorType: 'heavy',
    description: 'Heavily armored treaded war machine.',
  },
};

export const FACTION_NAMES: Record<FactionId, string> = {
  survivor: 'Survivor Corps',
  militia: 'Militia',
  tech: 'Tech Division',
  enemy: 'The Wasteland',
};

export const FACTION_COLORS: Record<FactionId, number> = {
  survivor: 0x4ade80,
  militia: 0xf97316,
  tech: 0x06b6d4,
  enemy: 0xb91c1c,
};

// Convert a hex number to a css color string
export function hexToCss(hex: number): string {
  return '#' + hex.toString(16).padStart(6, '0');
}

// Apply level scaling to base stats. Level 1 = base, 2 = +30% HP +20% DMG,
// 3 = +70% HP +50% DMG.
export function leveledStats(def: UnitDef, level: number): { hp: number; dmg: number } {
  let hpMul = 1;
  let dmgMul = 1;
  if (level === 2) {
    hpMul = 1.3;
    dmgMul = 1.2;
  } else if (level >= 3) {
    hpMul = 1.7;
    dmgMul = 1.5;
  }
  return {
    hp: Math.round(def.hp * hpMul),
    dmg: Math.round(def.dmg * dmgMul),
  };
}

export const ALL_PLAYABLE: UnitTypeId[] = [
  'scout',
  'rifleman',
  'heavy',
  'medic',
  'biker',
  'bomber',
  'sniper',
  'combatBot',
  'warDrone',
  'mechWalker',
];

export const ALL_ENEMIES: UnitTypeId[] = [
  'zombie',
  'feral',
  'brute',
  'alpha',
  'killerBot',
  'robotTank',
];
